### ISSUE TITLE
0 value in the 'zoom in' input field fill the whole file with black

### ISSUE THREAD

**Issue by martin19** [martin19/cloudpaint#12]
Description:
Setting 0 as a value of 'zoom in' cause the whole file is covered in black
Environment:
Chrome Version 103.0.5060.66 (Official Build) (64-bit)
Preconditions:
1. Browser opened on [cloudpaint.com/photo](http://cloudpaint.com/photo)
2. At least one file added
Steps to do:
1. Type '0' into the 'zoom in' value input field (at the right side of the screen)
Actual result:
The whole area of the file is covered in black
Expected result:
The user can't set this value to 0
Repeatability:
100.0% 5/5

![inputbug](https://user-images.githubusercontent.com/4746984/176856795-a453e62e-8de6-4acc-b058-edadc66f2b0e.png)

**Comment by adamtrjn0** [comment]
.

**Comment by martin19** [comment]
fixed in next release
