### ISSUE TITLE
Value of '0' in width or/and height input fields freeze the app

### ISSUE THREAD

**Issue by adamtrjn0** [martin19/cloudpaint#13]
Title:
Value of '0' in width or/and height input fields freeze the app
Description:
When the user tries to create a new file while setting up width or/and height values as 0 the whole app freezes
Environment:
Chrome Version 103.0.5060.66

Preconditions:
1. Browser opened on [cloudpaint.com/photo](http://cloudpaint.com/photo)
2. At least one file created

Steps to do:
1.Click the file option in the top menu
2.Click the 'New...' option from the drop-down list
3.Set width or/and height value to '0'
4.Click the 'OK' button

Actual result:
The whole app freezes
Expected result:
An appropriate communicate is showing up
Repeatability:
100.0% 5/5

**Comment by adamtrjn0** [comment]
.

**Comment by martin19** [comment]
form validation will be implemented in next release.
