### ISSUE TITLE
Brush tool - setting opacity value to a number bigger than 100 causes graphics artifacts 

### ISSUE THREAD

**Issue by adamtrjn0** [martin19/cloudpaint#14]
Title:
Brush tool - setting opacity value to a number bigger than 100 causes graphics artifacts 
Description:
When the user sets the opacity value of the Brush tool to a number bigger than 100 (visibility of the artifacts is changing according to how big that value is i.e when the input value is 10000 they are more visible than when the value is 400), fields, where the tool was used, are not displayed properly
Environment:
Chrome Version 103.0.5060.66 (Official Build) (64-bit)
Preconditions:
1.Browser opened on cloudpaint.com/photo
2.At least one file created
Steps to do:
1.Select the "Brush" tool from the left menu by clicking on its icon (brush) with the left mouse button
2.Type value higher than 100 into the 'Opacity' input field from the top menu
3.Try to draw something on the workspace
Actual result:
The output is not correctly displayed, different graphic artifacts are introduced into the workspace
Expected result:
Inserted value is automatically changed to the default value i.e 100, no artifacts are introduced
Repeatability:
100.0% 5/5

**Comment by adamtrjn0** [comment]
![bugscreen](https://user-images.githubusercontent.com/86123523/176996993-eeb1b719-6066-4619-b883-18d3eaf64173.png)

**Comment by martin19** [comment]
That is interesting! bounds check should be sufficient to avoid.

**Comment by martin19** [comment]
entering out of bounds value is not possible anymore in next release.
