### ISSUE TITLE
FloodFill tool - user can't change the opacity value 

### ISSUE THREAD

**Issue by adamtrjn0** [martin19/cloudpaint#15]
Description:
The user isn't able to change the opacity value of a FloodFill tool, it simply doesn't change when moving the slider
Environment:
Chrome Version 103.0.5060.66 (Official Build) (64-bit)
Preconditions:
1. Browser opened on cloudpaint.com/photo
2. At least one file created

Steps to do:
1. Select the "FloodFill" tool from the left menu by clicking on its icon (bucket) with the left mouse button
2. Click the arrow button next to the opacity input field
3. Click and hold the slider that showed up and try to drag it into the left side of the screen 
Actual result:
Nothing happens, the opacity value stays the same
Expected result:
The opacity value has changed depending on the position of the slider
Repeatability:
100.0% 5/5

**Comment by martin19** [comment]
Thanks for reporting Adam!

**Comment by martin19** [comment]
fixed in next release
