### ISSUE TITLE
Fill using "pattern" option produce strange wrong output

### ISSUE THREAD

**Issue by martin19** [martin19/cloudpaint#2]
Filling some area of the image using the "pattern" option produce strange output completely diffrent from expected

Preconditions:

1.Browser opened on [cloudpaint.com/photo](http://cloudpaint.com/photo)

2.Some is photo uploaded

Steps to do:

1.Select the "lasso" tool

2.Select some area on the photo

3.Click the right mouse button on the selected area

4.Select the 'fill' option

5.From the 'use' dropdown list select the 'pattern' option

6.Select some pattern from drop-down menu

7.Click the 'OK' button

Actual result:

Selected area is filled with completely wrong output and the shape of the area is different than selected

Expected result:

Selected area is filled correctly with selected pattern, the shape of the area is corresponding to the selected shape

**Comment by adamtrjn0** [comment]
.

**Comment by martin19** [comment]
will be fixed in next release

**Comment by martin19** [comment]
Done
