### ISSUE TITLE
Rectangle tool - gradient fill - color picker - the slider inside the color picker doesn't work

### ISSUE THREAD

**Issue by adamtrjn0** [martin19/cloudpaint#23]
Description:
The user isn't able to use the slider inside the color picker

Environment:
Firefox 102.0 64 bit

Preconditions:
1. Browser opened on cloudpaint.com/photo
2. At least one file created

Steps to do:
1. Select the Rectangle tool
2. Click the drop-down menu list next to the 'Fill' option
3. Click the 'Fill-gradient' option
4. Click the color picker next to the 'Color' 
5. Click somewhere on the color picker's slider pallete

Actual result:
The color picker's slider isn't responding, the color doesn't change

Expected result:
The color changed based on the slider's area that has been clicked

Repeatability:
100.0% 10/10

**Comment by martin19** [comment]
You need to select a color stop handle by clicking on it before a color can be chosen.
