### ISSUE TITLE
Image - Image size - it isn't possible to uncheck the 'Scale Styles' checkbox

### ISSUE THREAD

**Issue by adamtrjn0** [martin19/cloudpaint#29]
Description:
The user can't uncheck the 'Scale Styles' checkbox 

Environment:
Chrome Version 103.0.5060.114 

Preconditions:
1.Browser opened on cloudpaint.com/photo
2.At least one layer created

Steps to do:
1.Click the 'Image' option from the top menu
2.Click the 'Image Size...' option from the drop-down list
3.Click the checkbox next to the 'Scale Styles'

Actual result:
Checkbox state stays the same

Expected result:
Checkbox state changes

Repeatability:
100.0% 5/5

**Comment by martin19** [comment]
will be fixed in next release
