### ISSUE TITLE
'gradient-linear' tool doesn't work

### ISSUE THREAD

**Issue by martin19** [martin19/cloudpaint#3]
gradient-linear' tool doesn't work, when used nothing happens

Preconditions:

1.Browser opened on [cloudpaint.com/photo](http://cloudpaint.com/photo)

2.At leat one layer created

Steps to do:

1.Click the 'linear-gradient' tool

2.Hold the left mouse button above on the layer

3.Perform mouse movement in some direction

4.Let go left mouse button

Actual result:

Nothing happens, the layer stays the same as before

Expected result:

Layer is covered by selected gradient

**Comment by adamtrjn0** [comment]
.

**Comment by martin19** [comment]
will be fixed in next release
