### ISSUE TITLE
It isn't possible to change text's colour

### ISSUE THREAD

**Issue by martin19** [martin19/cloudpaint#4]
User isn't able to change text's colour, after setting some colour and saving changes text is still in black
Environment:
Chrome Version 103.0.5060.53 (Official Build) (64-bit)
Preconditions:
1.Browser opened on https://cloudpaint.com/photo
2.At least one layer added to a project
Steps to do:
1.Select the "type" tool
2.Click and hold the left mouse button above the layer
3.Move the mouse in some direction
4.Let go left mouse button
5.Type some text
6.Select the text using two left mouse button clicks on it
7.From top menu select color change tool
8.Select some colour different than black
9.Click the 'OK' button
10.Click the 'accept button' (figuring as a tick icon in the top menu) button
Actual result:
The text colour doesn't change
Expected result:
The text colour is changed according to user's colour choice

**Comment by adamtrjn0** [comment]
.

**Comment by adamtrjn0** [comment]
.

**Comment by martin19** [comment]
will be fixed in next release
